
LR: 2.5e-4
NUM_ENVS: 4
NUM_STEPS: 128
TOTAL_TIMESTEPS: 5e5
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
num_updates_per_eval: 5e4
NUM_EVALS: 10

GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "tanh"
ENV_NAME: "CartPole-v1"
ANNEAL_LR: True
DEBUG: True